language: cpp
sudo: required
matrix:
    # This marks the build as failed as soon as something goes wrong
    fast_finish: true

    # Manually specify the matrix:
    # Test Qt4 on precise
    # test Qt5 on trusty (triggered via services: docker)
    include:
        - os: linux
          env: QT_VERSION=4
          compiler: gcc
        - os: linux
          env: QT_VERSION=4
          compiler: clang
        - os: linux
          services: docker
          env: QT_VERSION=5
          compiler: gcc
        - os: linux
          services: docker
          env: QT_VERSION=5
          compiler: clang
        - os: osx
          env: QT_VERSION=4
          compiler: clang
install:
 - _travis/install_dependencies
 - _travis/compile
script: _travis/test
